"""new tables

Revision ID: 8dfaa9d3e4c8
Revises: 
Create Date: 2022-10-02 23:50:29.074530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfaa9d3e4c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_details_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('showrun', sa.Text(), nullable=True),
    sa.Column('physicalports', sa.Text(), nullable=True),
    sa.Column('virtualports', sa.Text(), nullable=True),
    sa.Column('disabledports', sa.Text(), nullable=True),
    sa.Column('enabledports', sa.Text(), nullable=True),
    sa.Column('updated', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.Text(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('sw_version', sa.Text(), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('os_type', sa.Text(), nullable=True),
    sa.Column('chassis_sn', sa.Text(), nullable=True),
    sa.Column('uptime', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices_table')
    op.drop_table('device_details_table')
    # ### end Alembic commands ###
